import matplotlib.pyplot as plt

CSAH_res = '''mandspakslvdidlsslrdpagifelvevvgngtygqvykgrhvktgqlaaikvmdvtedeeeeikleinmlkkyshhrniatyygafikksppghddqlwlvmefcgagsitdlvkntkgntlkedwiayisreilrglahlhihhvihrdikgqnvlltenaevklvdfgvsaqldrtvgrrntfigtpywmapeviacdenpdatydyrsdlwscgitaiemaegapplcdmhpmralfliprnppprlkskkwskkffsfiegclvknymqrpsteqllkhpfirdqpnerqvriqlkdhidrtrkkrgekdeteyeysgseeeeeevpeqegepssivnvpgestlrrdflrlqqenkersealrrqqllqEQQLREQEEYKRQLLAERQKRIEQQKEQRRRLEEQQRREREARRQQEREQRRREQEEKRRLEELERRRKEEEERRRAEEEKRRVEREQEYIRRQLEEEQRHLEvlqqqllqeqamllecrwremeehrqaerlqrqlqqeqayllslqhdhrrphpqhsqqppppqqerskpsfhapepkahyepadrarevedrfrktnhsspeaqskqtgrvleppvpsrsesfsngnsesvhpalqrpaepqvpvrttsrspvlsrrdsplqgsgqqnsqagqrnstsieprllwerveklvprpgsgsssgssnsgsqpgshpgsqsgsgerfrvrsssksegspsqrlenavkkpedkkevfrplkpadltalakelravedvrpphkvtdysssseesgttdeedddveqegadestsgpedtraasslnlsngetesvktmivhddvesepamtpskegtlivrqtqsasstlqkhkssssftpfidprllqispssgttvtsvvgfscdgmrpeairqdptrkgsvvnvnptntrpqsdtpeirkykkrfnseilcaalwgvnllvgtesglmlldrsgqgkvyplinrrrfqqmdvleglnvlvtisgkkdklrvyylswlrnkilhndpevekkqgwttvgdlegcvhykvvkyerikflvialkssvevyawapkpyhkfmafksfgelvhkpllvdltveegqrlkviygscagfhavdvdsgsvydiylpthiqcsikphaiiilpntdgmellvcyedegvyvntygritkdvvlqwgemptsvayirsnqtmgwgekaieirsvetghldgvfmhkraqrlkflcerndkvffasvrsggssqvyfmtlgrtsllsw'''


plot_data = []


for s in CSAH_res:
	if(s.isupper()):
		print(s)
		plot_data.append(1)
	else:
		plot_data.append(0)

plt.plot(plot_data)
plt.title("CSAH SAH prediction")
plt.show()